name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Tomcat 9.0.109
        run: |
          wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.109/bin/apache-tomcat-9.0.109.tar.gz
          tar -xzf apache-tomcat-9.0.109.tar.gz
          mv apache-tomcat-9.0.109 $HOME/tomcat
          echo "Tomcat installed at $HOME/tomcat"

      - name: Download NetBeans CopyLibs
  run: |
    mkdir -p $HOME/ant-libs
    wget -O $HOME/ant-libs/org-netbeans-modules-java-j2seproject-copylibstask.jar \
    https://search.maven.org/remotecontent?filepath=org/netbeans/modules/org-netbeans-modules-java-j2seproject-copylibstask/1.50/org-netbeans-modules-java-j2seproject-copylibstask-1.50.jar

      - name: Build with Ant
        working-directory: ProyectoPrestamos
        run: ant -Dlibs.CopyLibs.classpath=$HOME/ant-libs/org-netbeans-modules-java-j2seproject-copylibstask.jar -Dj2ee.server.home=$HOME/tomcat clean build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectKey: examen-serrano_examen-serrano
          organization: examen-serrano
          token: ${{ secrets.SONAR_TOKEN }}

      - name: Export SonarCloud report to JSON
        run: |
          mkdir -p reports
          curl -u ${{ secrets.SONAR_TOKEN }} \
          -X GET "https://sonarcloud.io/api/issues/search?component=TuUsuario_ProyectoPrestamos" \
          -o reports/sonar_report.json
          echo "SonarCloud report saved in reports/sonar_report.json"